#!/bin/bash

echo "=== Alternative Pull Request Methods ==="
echo ""
echo "Since the direct comparison URL isn't working, let's try these alternatives:"
echo ""

echo "=== Method 1: Create PR from Your Fork ==="
echo "1. Go to: https://github.com/drinkingc0ffee/rayhunter-enhanced"
echo "2. Click on 'Pull requests' tab"
echo "3. Click 'New pull request'"
echo "4. Click 'compare across forks'"
echo "5. Set:"
echo "   - base repository: EFForg/rayhunter"
echo "   - base branch: main"
echo "   - head repository: drinkingc0ffee/rayhunter-enhanced"
echo "   - compare branch: simple-pr"
echo "6. Click 'Create pull request'"
echo ""

echo "=== Method 2: Direct PR Creation ==="
echo "1. Go to: https://github.com/EFForg/rayhunter"
echo "2. Click 'Pull requests' tab"
echo "3. Click 'New pull request'"
echo "4. Click 'compare across forks'"
echo "5. Manually select the repositories and branches"
echo ""

echo "=== Method 3: Alternative URL Formats ==="
echo "Try these URLs:"
echo ""
echo "URL 1: https://github.com/EFForg/rayhunter/pull/new"
echo "URL 2: https://github.com/drinkingc0ffee/rayhunter-enhanced/pull/new/simple-pr"
echo "URL 3: https://github.com/EFForg/rayhunter/compare/main...drinkingc0ffee:rayhunter-enhanced:simple-pr"
echo ""

echo "=== Method 4: Manual Fork Approach ==="
echo "If all else fails:"
echo "1. Go to https://github.com/EFForg/rayhunter"
echo "2. Click 'Fork' to create your own fork"
echo "3. Clone your fork: git clone https://github.com/drinkingc0ffee/rayhunter.git"
echo "4. Copy your enhanced files to the fork"
echo "5. Create PR from your fork to the original"
echo ""

echo "=== Current Status ==="
echo "Your simple-pr branch has been pushed to:"
echo "https://github.com/drinkingc0ffee/rayhunter-enhanced/tree/simple-pr"
echo ""
echo "The branch contains your enhanced code with proper history."
echo ""

echo "=== Debug Information ==="
echo "Current branch: $(git branch --show-current)"
echo "Latest commit: $(git log --oneline -1)"
echo "Upstream commit: $(git log --oneline upstream/main -1)"
echo ""

echo "=== Recommendation ==="
echo "Try Method 1 first (creating PR from your fork), as this often works"
echo "when direct comparison URLs have issues." 