[workspace]
resolver = "3"
members = [
    "check",
    "daemon",
    "installer",
    "lib",
    "rootshell",
    "telcom-parser",
    "tools",
]

[workspace.dependencies]
rayhunter = { path = "./lib" }
