services:
  rayhunter-build:
    build:
      context: ..
      dockerfile: docker-build/Dockerfile
    image: rayhunter-enhanced:latest
    container_name: docker-ubuntu-build
    hostname: docker-ubuntu-build
    
    # Keep container running
    tty: true
    stdin_open: true
    
    # Mount home directory for persistence (source code and build deps will be inside)
    volumes:
      - rayhunter-home:/home/rayhunter
    
    # Environment variables
    environment:
      - TERM=xterm-256color
      - COLORTERM=truecolor
      
    # Expose ports for web interface or debugging
    ports:
      - "8080:8080"  # Web interface
      - "8000:8000"  # Alternative port
      
    # Working directory
    working_dir: /home/rayhunter
    
    # Network configuration
    networks:
      - rayhunter-net

volumes:
  rayhunter-home:
    driver: local

networks:
  rayhunter-net:
    driver: bridge 